export const supabaseUrl = 'https://spklpvylzejyzxvmiunb.supabase.co';
export const supabaseAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwa2xwdnlsemVqeXp4dm1pdW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzcyNTU1MDUsImV4cCI6MTk5MjgzMTUwNX0.-AwNDsPRpp8huxBFLG8ZZBXmSomyawqy2c7aq0gm5zc';
export const supabaseRoleKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwa2xwdnlsemVqeXp4dm1pdW5iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3NzI1NTUwNSwiZXhwIjoxOTkyODMxNTA1fQ.3wh7aBvCr8fdvihp47ksTTZ5BMH2vlto13iBPLpNw1I';
