export const roster = [
  {
    id: 1,
    rank: 'CW2',
    firstName: 'Jordan',
    lastName: 'Kinsey',
    milEmail: 'jordan.e.kinsey.mil@army.mil',
    civEmail: 'jekinsey22@gmail.com',
    phone: '8476021481',
    isAdmin: true,
  },
  {
    id: 2,
    rank: '1SG',
    firstName: 'Chip',
    lastName: 'Brewster',
    milEmail: 'george.w.brewster6.mil@army.mil',
    civEmail: '',
    phone: '8476021481',
    isAdmin: true,
  },
  {
    id: 3,
    rank: 'SFC',
    firstName: 'Daniel',
    lastName: 'Jordan',
    milEmail: 'daniel.m.jordan.mil@mail.mil',
    civEmail: 'djordan218@gmail.com',
    phone: '9188144039',
    isAdmin: true,
  },
  {
    id: 4,
    rank: 'SFC',
    firstName: 'Stephanie',
    lastName: 'Osbourne',
    milEmail: 'stephanie.m.osbourne.mil@mail.mil',
    civEmail: 'stephanie.osbourne@gmail.com',
    phone: '9407823187',
    isAdmin: true,
  },
  {
    id: 5,
    rank: 'SFC',
    firstName: 'Jamie',
    lastName: 'Dubose',
    milEmail: 'jamie.a.dubose.mil@army.mil',
    civEmail: 'jsallen1985@gmail.com',
    phone: '2055317031',
    isAdmin: true,
  },
  {
    id: 6,
    rank: 'SFC',
    firstName: 'Steve',
    lastName: 'Sharp',
    milEmail: 'steven.r.sharp16.mil@army.mil',
    civEmail: 'ssharp@bethanyschools.com',
    phone: '4056024997',
    isAdmin: true,
  },
];
